"""Add author column to Item

Revision ID: 9148d10851f8
Revises: 
Create Date: 2025-07-07 12:11:36.717461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9148d10851f8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chemCurriculum', sa.Column('position', sa.Float(), nullable=True))
    op.create_unique_constraint(None, 'chemCurriculum', ['position'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chemCurriculum', type_='unique')
    op.drop_column('chemCurriculum', 'position')
    # ### end Alembic commands ###
